### ISSUE TITLE
Fix unmet peer dependency warning

### ISSUE THREAD

**Issue by VladimirMikulic** [wert-io/module-react-component#1]
**Issue**

When installing @wert-io/module-react-component with yarn, I get this warning:

![Screenshot_20221227_092408](https://user-images.githubusercontent.com/35997844/209636390-7c08f4ef-fadf-4fc0-a1e8-42ae4578bcb1.png)

**Suggested fix**

Given that  you have `@wert-io/widget-initializer` listed as a `dependency`, I'd suggest removing it from `peerDependencies`.

![Screenshot_20221227_092509](https://user-images.githubusercontent.com/35997844/209636637-dd818065-56c7-4e55-b713-da00de3bf402.png)

Thanks!

**Comment by onexsan** [comment]
Hello!

Apologies for the long reply and thank you for your suggestion. In the latest version of the package, we've removed the `@wert-io/widget-initializer` from the peer dependencies. Also, the new version provides hooks and uses Typescript, we'll be happy if you check it out!

**Comment by VladimirMikulic** [comment]
Better late than never I guess :joy:
